const ACTIVITY_TYPES={
    CODE_RUN:"CODE_RUN",
    CODE_SUCCESS:"CODE_SUCCESS",
    EASY_CHALLENGE_COMPLETED:"EASY_CHALLENGE_COMPLETED",
    MEDIUM_CHALLENGE_COMPLETED:"MEDIUM_CHALLENGE_COMPLETED",
    HARD_CHALLENGE_COMPLETED:"HARD_CHALLENGE_COMPLETED",
    ERROR_FIXED:"ERROR_FIXED",
    DAILY_CODING_BONUS:"DAILY_CODING_BONUS",
    PROJECT_MILESTONE_COMPLETED:"PROJECT_MILESTONE_COMPLETED",
    PROJECT_COMPLETED:"PROJECT_COMPLETED",

};
module.exports=ACTIVITY_TYPES;