const SCORE_REWARDS={
    CODE_RUN:2,
    CODE_SUCCESS:10,
    EASY_CHALLENGE_COMPLETED:50,
    MEDIUM_CHALLENGE_COMPLETED:100,
    HARD_CHALLENGE_COMPLETED:200,
    ERROR_FIXED:20,
    DAILY_CODING_BONUS:25,
    PROJECT_MILESTONE_COMPLETED:100,
    PROJECT_COMPLETED:300,
};
module.exports=SCORE_REWARDS;
    