const XP_REWARDS={
    CODE_RUN:2,
    CODE_SUCCESS:5,
    EASY_CHALLENGE_COMPLETED:25,
    MEDIUM_CHALLENGE_COMPLETED:50,
    HARD_CHALLENGE_COMPLETED:100,
    ERROR_FIXED:10,
    DAILY_CODING_BONUS:20,
    PROJECT_MILESTONE_COMPLETED:75,
    PROJECT_COMPLETED:200,
};
module.exports=XP_REWARDS;